import { PostData } from "@/types/PostData";

export const mockPostData: PostData[] = [
  {
    user_id: 1,
    url: "/mockImages/post9.jpg",
    title: 'Shibuya Crossing',
    prefecture: 13,  // Tokyo prefecture code
    city_name: 'Shibuya',
    description: 'A busy intersection in Tokyo with neon lights.',
    brand: 'Canon',
    camera_name: 'Canon EOS R5',
    latitude: 35.6595,
    longitude: 139.7005,
    snap_time: '2024-09-25T12:30:00',
    angle: 45,
    iso: '400',
    shutter_speed: '1/200',
    f_value: 5.6,
  },
  {
    user_id: 2,
    url: "/mockImages/post1.jpg",
    title: 'Tokyo Tower at Night',
    prefecture: 13,
    city_name: 'Minato',
    description: 'A night view of the iconic Tokyo Tower.',
    brand: 'Nikon',
    camera_name: 'Nikon Z7',
    latitude: 35.6586,
    longitude: 139.7454,
    snap_time: '2024-09-24T19:45:00',
    angle: 30,
    iso: '800',
    shutter_speed: '1/60',
    f_value: 4.0,
  },
  {
    user_id: 3,
    url: "/mockImages/post2.jpg",
    title: 'Cherry Blossoms at Ueno Park',
    prefecture: 13,
    city_name: 'Taito',
    description: 'Beautiful cherry blossoms in full bloom at Ueno Park.',
    brand: 'Sony',
    camera_name: 'Sony A7 III',
    latitude: 35.7138,
    longitude: 139.7731,
    snap_time: '2024-04-10T14:00:00',
    angle: 60,
    iso: '200',
    shutter_speed: '1/320',
    f_value: 2.8,
  },
  {
    user_id: 4,
    url: "/mockImages/post4.jpg",
    title: 'Asakusa Sensoji Temple',
    prefecture: 13,
    city_name: 'Taito',
    description: 'A famous historical temple in Tokyo.',
    brand: 'Fujifilm',
    camera_name: 'Fujifilm X-T4',
    latitude: 35.7148,
    longitude: 139.7967,
    snap_time: '2024-08-20T10:15:00',
    angle: 90,
    iso: '100',
    shutter_speed: '1/500',
    f_value: 3.5,
  },
  {
    user_id: 5,
    url: "/mockImages/post5.jpg",
    title: 'Odaiba Rainbow Bridge',
    prefecture: 13,
    city_name: 'Minato',
    description: 'A view of the Rainbow Bridge with the Tokyo skyline.',
    brand: 'Panasonic',
    camera_name: 'Panasonic Lumix GH5',
    latitude: 35.6275,
    longitude: 139.7713,
    snap_time: '2024-07-15T18:30:00',
    angle: 75,
    iso: '640',
    shutter_speed: '1/250',
    f_value: 4.5,
  },
];
